name: social_network
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc: ^8.1.1
  chewie: ^1.4.0
  cloud_firestore: ^4.4.5
  equatable: ^2.0.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^2.0.5
  http: ^0.13.5
  image_picker: ^0.8.7
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  uuid: ^3.0.7
  video_player: ^2.6.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
